
# Site settings
baseurl: ""



# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Instagram API
instagram_key:
instagram_caption: true

# SEO settings
title: Dario Ramalho
description: Dario is a Digital Product Designer at the BBC, and he is driven to make digital experiences inclusive and functional. His practice extends towards interactive and visual design
url: "http://dario.tv/"
email: darioramalho@gmail.com
twitter_username:
default_img:

# Profile settings
social:
  twitter:

include: ['_pages']
markdown: redcarpet
kramdown:
  input: GFM
       
# Build settings
exclude: [
 "node_modules",
 "gulpfile.js",
 "assets/js/app.js",
 "README.md",
 "Gemfile",
 "_assets",
 "vendor",
 "package.json",
 "Gemfile.lock"]

markdown: kramdown
permalink: /:year/:month/:day/:title/

# Gems
plugins: [jekyll-sitemap, octopress-autoprefixer]

# # Server Config options
# livereload: true     # You no longer need to include
# reload_port: 4000    # If you don't want to use the default port
